//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardBrowser.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cards
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cards()
        {
            this.CardsAbilitiesValues = new HashSet<CardsAbilitiesValues>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CardTypeId { get; set; }
        public Nullable<int> ResourceRequirement { get; set; }
        public string CardText { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> AttackValue { get; set; }
        public Nullable<int> StrengthValue { get; set; }
        public int CardRarityId { get; set; }
    
        public virtual CardRarities CardRarities { get; set; }
        public virtual CardTypes CardTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CardsAbilitiesValues> CardsAbilitiesValues { get; set; }
    }
}
