//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardBrowser.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardsAbilitiesValues
    {
        public int Id { get; set; }
        public int CardId { get; set; }
        public Nullable<int> CardAbilityTypeId { get; set; }
        public Nullable<int> AbilityValue { get; set; }
    
        public virtual CardAbilityTypes CardAbilityTypes { get; set; }
        public virtual Cards Cards { get; set; }
    }
}
